### ISSUE TITLE
Bug: Javascript Error on Startup

### ISSUE THREAD

**Issue by abargmann** [Kong/insomnia#1759]
- Insomnia Version: 7.0.2
- Operating System: 10.13.2

## Details

On startup, I receive the following:

![image](https://user-images.githubusercontent.com/1842516/67987735-66143f00-fbeb-11e9-9702-a0b2b59c562b.png)

**Comment by gschier** [comment]
Can you please specify your operating system version?

**Comment by gschier** [comment]
Does this still happen on 7.0.5?

**Comment by Isanderthul** [comment]
I am getting a similar issue on 7.0.6
```
Uncaught Exception:
Error: dlopen(/var/folders/d5/7bn7zsps77d2mqh42mqc0lx80000gn/T/.com.insomnia.app.sSgfBb, 1): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/opt/curl/lib/libcurl.dylib
  Reason: image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)
```

I found that `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` does not exist, however `/usr/local/opt/curl/lib/libcurl.dylib` makes reference to it. So `/usr/local/opt/curl/lib/libcurl.dylib` is not correctly pointing to the current `libssl.1.1.dylib`. 
To solve my issue I did a `brew upgrade curl`

**Comment by IOT4NDBS** [comment]
Thanks, this helped me a lot. Got the same problem and cloud fix it with `brew upgrade curl`

**Comment by gschier** [comment]
This should have been fixed a few versions ago 👍
