### ISSUE TITLE
[Bug] Issues with "path" argument for POST requests when importing Postman collection 

### ISSUE THREAD

**Issue by TheSecurityBug** [Kong/insomnia#1820]
Hey Insomnia devs. Firstly, just wanted to say just how astonishingly awesome Insomnia is. By far the best GUI REST client out there. Thank you so much for your hard work.

I've had issues importing a Postman (v2 I believe) collection into Insomnia. The collection is here:
https://github.com/sophoslabs/intelix-postman

There seems to be an issue with how the "path" argument is parsed. When I click on the **Intelix > Analysis > Dynamic > POST Dynamic Analysis** request (or any other POST request except the Congnito AccessToken requst), I receive encounter a "Failed to render RequestPane"  error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at basename (path.js:1299:5)
    at FileInputButton.render (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:36034:75)
    at Qg (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150070:192)
    at Og (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150069:264)
    at Tg (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150077:30)
    at bi (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150129:22)
    at ci (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150130:284)
    at Di (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150146:348)
    at Yh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:150145:144)
```

The steps to reproduce are:

1. Import Intelix.postman_collection.json into Insomnia from https://github.com/sophoslabs/intelix-postman
2. Click on any POST request except "Congnito AccessToken"

I am using Insomnia 7.0.5 on macOS 10.14.6

An example of an item in the .json that causes this issue is as follows:
```
{
	"name": "Dynamic analysis",
	"request": {
		"method": "POST",
		"header": [
			{
				"key": "Authorization",
				"value": "{{access_token}}"
			},
			{
				"key": "Content-Type",
				"name": "Content-Type",
				"type": "text",
				"value": "application/x-www-form-urlencoded"
			},
			{
				"key": "X-Correlation-Id",
				"type": "text",
				"value": "test",
				"disabled": true
			}
		],
		"body": {
			"mode": "formdata",
			"formdata": [
				{
					"key": "file",
					"type": "file",
					"src": []
				}
			]
		},
		"url": {
			"raw": "https://{{region}}.{{base_url}}/analysis/file/dynamic/v1",
			"protocol": "https",
			"host": [
				"{{region}}",
				"{{base_url}}"
			],
			"path": [
				"analysis",
				"file",
				"dynamic",
				"v1"
			]
		}
	},
	"response": []
}
```

However an item that doesn't cause this error is as follows:

```
{
	"name": "Get By JobId (Dynamic)",
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "4a11213f-30c5-4535-bcf8-ea38d999dcf3",
				"exec": [
					"pm.globals.set(\"job_id\", \"00000000000000000000000000000000\");",
					""
				],
				"type": "text/javascript"
			}
		}
	],
	"request": {
		"method": "GET",
		"header": [
			{
				"key": "Authorization",
				"type": "text",
				"value": "{{access_token}}"
			}
		],
		"url": {
			"raw": "https://{{region}}.{{base_url}}/analysis/file/dynamic/v1/reports/{{job_id}}",
			"protocol": "https",
			"host": [
				"{{region}}",
				"{{base_url}}"
			],
			"path": [
				"analysis",
				"file",
				"dynamic",
				"v1",
				"reports",
				"{{job_id}}"
			]
		}
	},
	"response": []
}
```

Both provide the "path" argument as an array rather than a string which the error highlights as the cause of the issue.

So there seems to be some difference between how a POST and a GET request is parsed.

I hope this is enough information. Happy to provide more if needed.

**Comment by yaoweiprc** [comment]
Sorry for the late reply — we've had a backlog of bugs. I’ve verified that this issue has already been resolved in the latest version of Insomnia.
